== Vert.x gRPC Client

The Vert.x gRPC Client provides a gRPC request/response oriented API as well as a generated client approach.

=== Using Vert.x gRPC Client

To use Vert.x gRPC Client, add the following dependency to the _dependencies_ section of your build descriptor:

* Maven (in your `pom.xml`):

[source,xml,subs="+attributes"]
----
<dependency>
  <groupId>io.vertx</groupId>
  <artifactId>vertx-grpc-client</artifactId>
  <version>${maven.version}</version>
</dependency>
----

* Gradle (in your `build.gradle` file):

[source,groovy,subs="+attributes"]
----
dependencies {
  compile 'io.vertx:vertx-grpc-client:${maven.version}'
}
----

=== Creating a gRPC client

You can easily create the gRPC client

[source,java]
----
{@link examples.GrpcClientExamples#createClient}
----

[[idiomatic-client]]
=== Idiomatic client API generation

The <<vertx-grpc-protoc-plugin,Vert.x gRPC protoc plugin>> generates idiomatic client code:

- `examples/Greeter.java`
- `examples/GreeterClient.java`
- `examples/GreeterGrpcClient.java`

An idiomatic client wraps a `GrpcClient` and provides a Vert.x idiomatic API to interact with the service

The `Greeter` interface defines the primary _contract_ of the service:

[source,java]
----
public interface Greeter {

  Future<examples.grpc.HelloReply> sayHello(examples.grpc.HelloRequest request);

}
----

The `GreeterClient` interface extends the `Greeter` contract and annotates it with Vert.x codegen annotations, providing
the option to perform further code generation such as generating an _RxJava_ or a _Mutiny_ client.

[source,java]
----
@io.vertx.codegen.annotations.VertxGen
public interface GreeterClient extends Greeter {

  @io.vertx.codegen.annotations.GenIgnore(io.vertx.codegen.annotations.GenIgnore.PERMITTED_TYPE)
  Future<examples.grpc.HelloReply> sayHello(examples.grpc.HelloRequest request);
}
----

The `GreeterGrpcClient` interface extends `GreeterClient` and provides an implementation that uses the Vert.x gRPC Client to
interact with a service:

[source,java]
----
{@link examples.GrpcClientExamples#createIdiomaticClient}
----

==== Unary services

Unary services returns a Vert.x `Future`

[source,java]
----
{@link examples.GrpcClientExamples#unaryIdiomaticClient}
----

==== Streaming requests

Streaming requests use a lambda passed a Vert.x `WriteStream` of messages sent to the service

[source,java]
----
{@link examples.GrpcClientExamples#streamingRequestIdiomaticClient1}
----

Alternatively, you can pass a stream of messages to be sent to the service

[source,java]
----
{@link examples.GrpcClientExamples#streamingRequestIdiomaticClient2}
----

==== Streaming responses

Streaming responses get a Vert.x `ReadStream` of messages sent by the service

[source,java]
----
{@link examples.GrpcClientExamples#streamingResponseIdiomaticClient}
----

=== RxJava client wrapper generation

If you want to generate your client with Vert.x codegen annotations, you can use the option in `vertx-grpc-protoc-plugin2` to
generate a client service interface annotated with Vert.x codegen annotations. To do this
you need to pass `--vertx-codegen` option to the to the `vertx-grpc-protoc-plugin`:

[source,xml]
----
<protocPlugin>
  <id>vertx-grpc-protoc-plugin2</id>
  <groupId>io.vertx</groupId>
  <artifactId>vertx-grpc-protoc-plugin2</artifactId>
  <version>${stack.version}</version>
  <mainClass>io.vertx.grpc.plugin.VertxGrpcGenerator</mainClass>
  <args>
    <arg>--vertx-codegen</arg>
  </args>
</protocPlugin>
----

The generated client service interface will be annotated with `@io.vertx.codegen.annotations.VertxGen`.

[source,java]
----
@io.vertx.codegen.annotations.VertxGen
public interface GreeterClient {
  ...
}
----

Therefore, a Vert.x codegen processor can process it, as such a Vert.x RxJava generator will generate an RxJava client wrapper
with idiomatic RxJava API.

Here is a Maven configuration example:

[source,xml]
----
<plugin>
  <artifactId>maven-compiler-plugin</artifactId>
  <executions>
    <execution>
      <id>default-compile</id>
      <configuration>
        <annotationProcessorPaths>
          <annotationProcessorPath>
            <groupId>io.vertx</groupId>
            <artifactId>vertx-codegen</artifactId>
            <classifier>processor</classifier>
            <version>${vertx.version}</version>
          </annotationProcessorPath>
          <annotationProcessorPath>
            <groupId>io.vertx</groupId>
            <artifactId>vertx-rx-java3-gen</artifactId>
            <version>${vertx.version}</version>
          </annotationProcessorPath>
        </annotationProcessorPaths>
      </configuration>
    </execution>
  </executions>
</plugin>
----

The generated can be then used

[source,java]
----
// Use the RxJava version
GreeterClient client = io.grpc.examples.rxjava3.helloworld.GreeterClient.create(grpcClient, SocketAddress.inetSocketAddress(8080, "localhost"));

// Get a Single instead of a Future
Single<HelloReply> reply = client.sayHello(HelloRequest.newBuilder().setName("World").build());

Flowable<HelloRequest> requestStream = Flowable.just("World", "Monde", "Mundo")
      .map(name -> HelloRequest.newBuilder().setName(name).build());

// Use Flowable instead of Vert.x streams
Flowable<String> responseStream = client
  .sayHelloStreaming(stream)
  .map(HelloReply::getMessage);
----

NOTE: this requires RxJava version of GrpcClient

=== Client request/response API

The gRPC request/response client API provides an alternative way to interact with a server without the need of a generated stub.

==== Addressing a gRPC service method

You will use a `{@link io.vertx.grpc.common.ServiceMethod}` to address a gRPC service method

[source,java]
----
{@link examples.GrpcClientExamples#createServiceMethod}
----

However, most of the time you can use `ServiceMethod` generated constants by the <<vertx-grpc-protoc-plugin,Vert.x gRPC protoc plugin>>:

[source,java]
----
{@link examples.GrpcClientExamples#reuseServiceMethod}
----

==== Request/response

Interacting with a gRPC server involves the creation of a request to the remote gRPC service.

[source,java]
----
{@link examples.GrpcClientExamples#sendRequest}
----

The `{@link io.vertx.grpc.client.GrpcClientRequest#response}` holds the response and the
`{@link io.vertx.grpc.client.GrpcClientResponse#last}` holds the result

[source,java]
----
{@link examples.GrpcClientExamples#receiveResponse}
----

Future composition can combine all the previous steps together in a compact fashion

[source,java]
----
{@link examples.GrpcClientExamples#requestResponse}
----

==== Streaming request

Streaming requests involve calling `{@link io.vertx.grpc.client.GrpcClientRequest#write}` for each element of the stream
and using `{@link io.vertx.grpc.client.GrpcClientRequest#end()}` to end the stream

[source,java]
----
{@link examples.GrpcClientExamples#streamingRequest}
----

==== Streaming response

You can set handlers to process response events of a streaming response

[source,java]
----
{@link examples.GrpcClientExamples#streamingResponse}
----

==== Bidi request/response

A bidi request/response is simply the combination of a streaming request and a streaming response.

=== Flow control

Whether you use the request/response API or the idiomatic client API, you interact with stream which are back pressured Vert.x streams.

You can check the writability of a request and set a drain handler

[source,java]
----
{@link examples.GrpcClientExamples#requestFlowControl}
----

You can pause/resume/fetch a response to precisely control the message you read.

[source,java]
----
{@link examples.GrpcClientExamples#responseFlowControl}
----

NOTE: you can learn more about Vert.x streams in the Vert.x Core documentation

=== Timeout and deadlines

The gRPC client handles timeout and deadlines, setting a timeout on a gRPC request instructs the client to send the timeout
information to make the server aware that the client desires a response within a defined time.

In addition, the client shall be configured to schedule a deadline: when a timeout is set on a request, the client schedules
locally a timer to cancel the request when the response has not been received in time.

[source,java]
----
{@link examples.GrpcClientExamples#requestWithDeadline}
----

The timeout can also be set on a per-request basis.

[source,java]
----
{@link examples.GrpcClientExamples#requestWithDeadline2}
----

=== Cancellation

You can call `{@link io.vertx.grpc.client.GrpcClientRequest#cancel}` to cancel a request

[source,java]
----
{@link examples.GrpcClientExamples#requestCancellation}
----

NOTE: cancellation sends an HTTP/2 reset frame to the server

=== Client side load balancing

The gRPC Client can be configured to perform client side load balancing.

==== DNS based load balancing

DNS based load balancing works with DNS queries resolving a single host to multiple IP addresses (usually `A` records).

You can set a load balancer to enable DNS-based load balancing

[source,java]
----
{@link examples.GrpcClientExamples#clientSideDNSBasedLoadBalancing}
----

The usual load balancing strategies are available, you can refer to the Vert.x HTTP client side load balancing documentation
to configure them.

==== Address based load balancing

Address based load balancing relies on the Vert.x address resolver to resolve a single address to multiple host/port socket addresses.

You can set an address resolver to enable load balancing, the Vert.x Service Resolver implements a few address resolver, e.g. like  a Kubernetes resolver.

[source,java]
----
{@link examples.GrpcClientExamples#clientSideAddressBasedLoadBalancing1}
----

Unlike DNS based load balancing, address based load balancing uses an abstract {@link io.vertx.core.net.Address} instead of
a {@link io.vertx.core.net.SocketAddress}. The address resolver implementation resolves address to a list of socket addresses.

The Vert.x Servicer Resolver defines a `ServiceAddress`.

[source,java]
----
{@link examples.GrpcClientExamples#clientSideAddressBasedLoadBalancing2}
----

You can refer to the Vert.x Service Resolver project documentation for more details.

=== JSON wire format

gRPC implicitly assumes the usage of the https://protobuf.dev[Protobuf] wire format.

The Vert.x gRPC client supports the JSON wire format as well.

You can call a JSON service method with the `application/grpc+json` content-type.

[source,java]
----
{@link examples.GrpcClientExamples#jsonWireFormat01}
----

The client will send `application/grpc+json` requests.

NOTE: JSON encoding/decoding is achieved by `com.google.protobuf:protobuf-java-util` library.

Anemic JSON is also supported with Vert.x `JsonObject`

[source,java]
----
{@link examples.GrpcClientExamples#jsonWireFormat02}
----

You can also specify the JSON wire format when creating an idiomatic client

[source,java]
----
{@link examples.GrpcClientExamples#createClientIdiomaticJson}
----

=== Compression

You can compress request messages by setting the request encoding *prior* before sending any message

[source,java]
----
{@link examples.GrpcClientExamples#requestCompression}
----

=== Decompression

Decompression is achieved transparently by the client when the server sends encoded responses.

=== Message level API

The client provides a message level API to interact directly with protobuf encoded gRPC messages.

TIP: the client message level API can be combined with the server message level API to write a gRPC intermediary for which
messages are opaque such as a reverse proxy.

Such API is useful when you are not interested in the content of the messages, and instead you want to forward them to
another service, e.g. you are writing a proxy.

[source,java]
----
{@link examples.GrpcClientExamples#protobufLevelAPI}
----

You can also set a `messageHandler` to handle `{@link io.vertx.grpc.common.GrpcMessage}`, such messages preserve the server encoding.

[source,java]
----
{@link examples.GrpcClientExamples#messageLevelAPI}
----

The `{@link io.vertx.grpc.client.GrpcClientRequest#writeMessage}` and `{@link io.vertx.grpc.client.GrpcClientRequest#endMessage}` will
handle the message encoding:

- when the message uses the response encoding, the message is sent as is
- when the message uses a different encoding, it will be encoded, e.g. compressed or uncompressed
