== Vert.x gRPC Client

Vert.x gRPC Client is a gRPC client powered by Vert.x HTTP client.

This client provides a gRPC request/response oriented API as well as a generated stub approach with a gRPC Channel

=== Using Vert.x gRPC Client

To use Vert.x gRPC Client, add the following dependency to the _dependencies_ section of your build descriptor:

* Maven (in your `pom.xml`):

[source,xml,subs="+attributes"]
----
<dependency>
  <groupId>io.vertx</groupId>
  <artifactId>vertx-grpc-client</artifactId>
  <version>${maven.version}</version>
</dependency>
----

* Gradle (in your `build.gradle` file):

[source,groovy,subs="+attributes"]
----
dependencies {
  compile 'io.vertx:vertx-grpc-client:${maven.version}'
}
----

=== Creating a gRPC client

You can easily create the gRPC client

[source,java]
----
{@link examples.GrpcClientExamples#createClient}
----

=== Client request/response API

The gRPC request/response client API provides an alternative way to interact with a server without the need of a generated stub.

==== Request/response

Interacting with a gRPC server involves creating a request to the remote gRPC service

[source,java]
----
{@link examples.GrpcClientExamples#sendRequest}
----

`{@link io.vertx.grpc.common.ServiceMethod}` constants are <<ServiceMethodConstants,generated>> by the Vert.x gRPC protoc plugin.

The `{@link io.vertx.grpc.client.GrpcClientRequest#response}` holds the response and the
`{@link io.vertx.grpc.client.GrpcClientResponse#last}` holds the result

[source,java]
----
{@link examples.GrpcClientExamples#receiveResponse}
----

Future composition can combine all the previous steps together in a compact fashion

[source,java]
----
{@link examples.GrpcClientExamples#requestResponse}
----

==== Streaming request

Streaming requests involve calling `{@link io.vertx.grpc.client.GrpcClientRequest#write}` for each element of the stream
and using `{@link io.vertx.grpc.client.GrpcClientRequest#end()}` to end the stream

[source,java]
----
{@link examples.GrpcClientExamples#streamingRequest}
----

==== Streaming response

You can set handlers to process response events of a streaming response

[source,java]
----
{@link examples.GrpcClientExamples#streamingResponse}
----

==== Bidi request/response

A bidi request/response is simply the combination of a streaming request and a streaming response.

=== Flow control

Request and response are back pressured Vert.x streams.

You can check the writability of a request and set a drain handler

[source,java]
----
{@link examples.GrpcClientExamples#requestFlowControl}
----

You can pause/resume/fetch a response

[source,java]
----
{@link examples.GrpcClientExamples#responseFlowControl}
----

=== Timeout and deadlines

The gRPC client handles timeout and deadlines, setting a timeout on a gRPC request instructs the client to send the timeout
information to make the server aware that the client desires a response within a defined time.

In addition, the client shall be configured to schedule a deadline: when a timeout is set on a request, the client schedules
locally a timer to cancel the request when the response has not been received in time.

[source,java]
----
{@link examples.GrpcClientExamples#requestWithDeadline}
----

The timeout can also be set on a per-request basis.

[source,java]
----
{@link examples.GrpcClientExamples#requestWithDeadline2}
----

=== Cancellation

You can call `{@link io.vertx.grpc.client.GrpcClientRequest#cancel}` to cancel a request

[source,java]
----
{@link examples.GrpcClientExamples#requestCancellation}
----

NOTE: cancellation sends an HTTP/2 reset frame to the server

=== JSON wire format

gRPC implicitly assumes the usage of the https://protobuf.dev[Protobuf] wire format.

The Vert.x gRPC client supports the JSON wire format as well.

You can call a JSON service method with the `application/grpc+json` content-type.

[source,java]
----
{@link examples.GrpcClientExamples#jsonWireFormat01}
----

NOTE: JSON encoding/decoding is achieved by `com.google.protobuf:protobuf-java-util` library.

Anemic JSON is also supported with Vert.x `JsonObject`

[source,java]
----
{@link examples.GrpcClientExamples#jsonWireFormat02}
----

=== Compression

You can compress request messages by setting the request encoding *prior* before sending any message

[source,java]
----
{@link examples.GrpcClientExamples#requestCompression}
----

=== Decompression

Decompression is achieved transparently by the client when the server sends encoded responses.

=== Message level API

The client provides a message level API to interact directly with protobuf encoded gRPC messages.

TIP: the client message level API can be used with the server message level API to write a gRPC reverse proxy

Such API is useful when you are not interested in the content of the messages, and instead you want to forward them to
another service, e.g. you are writing a proxy.

[source,java]
----
{@link examples.GrpcClientExamples#protobufLevelAPI}
----

You can also set a `messageHandler` to handle `{@link io.vertx.grpc.common.GrpcMessage}`, such messages preserve the server encoding.

[source,java]
----
{@link examples.GrpcClientExamples#messageLevelAPI}
----

The `{@link io.vertx.grpc.client.GrpcClientRequest#writeMessage}` and `{@link io.vertx.grpc.client.GrpcClientRequest#endMessage}` will
handle the message encoding:

- when the message uses the response encoding, the message is sent as is
- when the message uses a different encoding, it will be encoded, e.g. compressed or uncompressed

=== Client stub API

In addition to the request/response API, the Vert.x gRPC protoc plugin idiomatic service clients.

A client wraps a `GrpcClient` and provides Vert.x idiomatic API to interact with the service

[source,java]
----
{@link examples.GrpcClientExamples#createClientStub}
----

You can also specify the JSON wire format when creating a stub

[source,java]
----
{@link examples.GrpcClientExamples#createClientStubJson}
----

The client will send `application/grpc+json` requests.

==== Unary services

Unary services returns a Vert.x `Future`

[source,java]
----
{@link examples.GrpcClientExamples#unaryStub}
----
==== Streaming requests

Streaming requests use a lambda passed a Vert.x `WriteStream` of messages sent to the service

[source,java]
----
{@link examples.GrpcClientExamples#streamingRequestStub}
----

==== Streaming responses

Streaming responses get a Vert.x `ReadStream` of messages sent by the service

[source,java]
----
{@link examples.GrpcClientExamples#streamingResponseStub}
----
