[[grpc-eventbus]]
== gRPC EventBus transport

The gRPC EventBus transport allows gRPC services to communicate over the Vert.x EventBus instead of HTTP/2.
The transport supports both protobuf and JSON wire formats and works with generated gRPC service stubs.

=== Using the EventBus transport

To use the EventBus transport, add the following dependency:

[tabs]
====
pom.xml::
+
[source,xml,subs="+attributes"]
----
<dependency>
  <groupId>io.vertx</groupId>
  <artifactId>vertx-grpc-event-bus</artifactId>
  <version>${maven.version}</version>
</dependency>
----

build.gradle::
+
[source,groovy,subs="+attributes"]
----
dependencies {
  compile 'io.vertx:vertx-grpc-event-bus:${maven.version}'
}
----
====

=== EventBus server

The `EventBusGrpcServer` registers EventBus consumers for each service and dispatches incoming messages to service handlers. It implements `GrpcServer`, so generated service stubs work out of the box.

[source,java]
----
{@link examples.GrpcEventBusExamples#createServer}
----

You can add generated services just like a regular gRPC server:

[source,java]
----
{@link examples.GrpcEventBusExamples#serverWithService}
----

The server registers an EventBus consumer using the service's fully qualified name as the address (e.g. `examples.grpc.Greeter`) and routes to specific methods using the `action` delivery header.

=== EventBus client

The `EventBusGrpcClient` sends gRPC requests over the EventBus. It implements `GrpcClientService`, so generated client stubs work out of the box.

[source,java]
----
{@link examples.GrpcEventBusExamples#createClient}
----

You can use generated client stubs:

[source,java]
----
{@link examples.GrpcEventBusExamples#clientWithService}
----

=== JSON wire format

By default the transport uses protobuf encoding. You can switch to JSON by passing the wire format when creating the client:

[source,java]
----
{@link examples.GrpcEventBusExamples#jsonWireFormat}
----

The server automatically detects the wire format from the `grpc-wire-format` delivery header and responds in the same format.

=== Limitations

The EventBus transport only supports unary (request/response) calls. Streaming is not supported because the Vert.x EventBus does not currently support streaming messages at the moment.
