== Vert.x gRPC/IO Server

Vert.x gRPC/IO Server extends the Vert.x gRPC server with _grpc-java_ integration.

This server provides compatibility with the _grpc-java_ generated stub approach with a service bridge.

=== Using Vert.x gRPC/IO Server

To use Vert.x gRPC/IO Server, add the following dependency to the _dependencies_ section of your build descriptor:

[tabs]
====
pom.xml::
+
[source,xml,subs="+attributes"]
----
<dependency>
  <groupId>io.vertx</groupId>
  <artifactId>vertx-grpcio-server</artifactId>
  <version>${maven.version}</version>
</dependency>
----

build.gradle::
+
[source,groovy,subs="+attributes"]
----
dependencies {
  compile 'io.vertx:vertx-grpcio-server:${maven.version}'
}
----
====

=== Service bridge

The Vert.x gRPC Server can bridge a gRPC service to use with _grpc-java_ generated server classes.

[source,java]
----
{@link examples.GrpcIoServerExamples#stubExample}
----

The bridge supports deadline automatic cancellation: when a gRPC request carrying a timeout is received, a deadline is associated with the `io.grpc.Context` an can be obtained from the current context. This deadline automatically cancels the request in progress when its associated timeout fires.

[[idiomatic-server-io]]
=== Idiomatic gRPC/IO service

The <<vertx-grpc-protoc-plugin,Vert.x gRPC protoc plugin>> supports the generation of gRPC/IO client code:

- `examples/Greeter.java`
- `examples/GreeterService.java`
- `examples/GreeterGrpcIo.java`

By default, `GreeterGrpcIo` is not generated, to activate it you need to tell the Vert.x gRPC protoc plugin to generate it:

[source,xml]
----
<protocPlugin>
  <id>vertx-grpc-protoc-plugin2</id>
  <groupId>io.vertx</groupId>
  <artifactId>vertx-grpc-protoc-plugin2</artifactId>
  <version>${stack.version}</version>
  <mainClass>io.vertx.grpc.plugin.VertxGrpcGenerator</mainClass>
  <args>
    <arg>--grpc-io</arg>
  </args>
</protocPlugin>
----

The `GreeterGrpcIo` provides a bindable service that uses the Vert.x gRPC/IO Server to expose the service:

[source,java]
----
{@link examples.GrpcIoServerExamples#idiomaticStubExample}
----

You can read the <<idiomatic-server, idiomatic server>> section to learn more about it.

=== gRPC Reflection APIs

Support for the https://grpc.io/docs/guides/reflection/[gRPC reflection APIs] can be added to your Vert.x gRPC Server.

[source,java]
----
{@link examples.GrpcIoServerExamples#reflectionExample}
----

You can then use tools like https://github.com/fullstorydev/grpcurl[gRPCurl] to explore and invoke your gRPC APIs.

[source,bash]
----
grpcurl -plaintext localhost:50051 list

grpcurl -plaintext localhost:50051 describe .helloworld.HelloRequest

grpcurl -plaintext -d '{"name": "Vert.x"}' localhost:50051 helloworld.Greeter
----
