== Vert.x gRPC Server

Vert.x gRPC Server is a gRPC server powered by Vert.x HTTP server superseding the integrated Netty based gRPC client.

This server provides a gRPC request/response oriented API as well as a generated stub approach with the Vert.x gRPC Generator.

=== Using Vert.x gRPC Server

To use Vert.x gRPC Server, add the following dependency to the _dependencies_ section of your build descriptor:

* Maven (in your `pom.xml`):

[source,xml,subs="+attributes"]
----
<dependency>
  <groupId>io.vertx</groupId>
  <artifactId>vertx-grpc-server</artifactId>
  <version>${maven.version}</version>
</dependency>
----

* Gradle (in your `build.gradle` file):

[source,groovy,subs="+attributes"]
----
dependencies {
  compile 'io.vertx:vertx-grpc-server:${maven.version}'
}
----

=== Creating a gRPC server

A `{@link io.vertx.grpc.server.GrpcServer}` is a `Handler<HttpServerRequest>` and can be used as an HTTP server request handler.

[source,java]
----
{@link examples.GrpcServerExamples#createServer}
----

[TIP]
====
A `GrpcServer` can be used within a Vert.x Web router:

[source,java]
----
route.consumes("application/grpc").handler(rc -> grpcServer.handle(rc.request()));
----
====

==== gRPC-Web protocol

The Vert.x gRPC Server supports the gRPC-Web protocol by default.

To disable the gRPC-Web protocol support, configure options with {@link io.vertx.grpc.server.GrpcServerOptions#setGrpcWebEnabled GrpcServerOptions#setGrpcWebEnabled(false)} and then create a server with {@link io.vertx.grpc.server.GrpcServer#server(io.vertx.core.Vertx, io.vertx.grpc.server.GrpcServerOptions) GrpcServer#server(vertx, options)}.

[TIP]
====
If your website server and the gRPC server are different, you have to configure the gRPC server for CORS.
This can be done with a Vert.x Web router and the CORS handler:

[source,java]
----
CorsHandler corsHandler = CorsHandler.create()
  .addRelativeOrigin("https://www.mycompany.com")
  .allowedHeaders(Set.of("keep-alive","user-agent","cache-control","content-type","content-transfer-encoding","x-custom-key","x-user-agent","x-grpc-web","grpc-timeout"))
  .exposedHeaders(Set.of("x-custom-key","grpc-status","grpc-message"));
router.route("/com.mycompany.MyService/*").handler(corsHandler);
----
====

==== gRPC Transcoding

gRPC transcoding is a feature that enables mapping between HTTP/JSON requests and gRPC services.

gRPC transcoding allows your services to accept both gRPC and HTTP/JSON requests, providing greater flexibility. This feature is particularly useful when:

* You want to expose your gRPC services to clients that don't support gRPC
* You need to support both traditional REST APIs and gRPC endpoints
* You want to leverage gRPC's efficiency while maintaining HTTP/JSON compatibility

You do not need specific configuration for gRPC transcoding since it is serves HTTP protocol. However, services must
be deployed with additional configuration such as the mount path to have transcoding operational.

==== Transcoding error handling

If an error occurs during transcoding, the server will return an HTTP error response with the appropriate status code.
Most grpc status codes are mapped to the corresponding HTTP status codes on best effort basis. If the status code is not mapped,
the server will return a 500 Internal Server Error.

|===
|gRPC Status Code | HTTP Status Code | Description
|OK | 200 | The operation completed successfully.
|CANCELLED | 408 | The operation was cancelled (typically by the caller).
|UNKNOWN | 500 | Unknown error.
|INVALID_ARGUMENT | 400 | Client specified an invalid argument.
|DEADLINE_EXCEEDED | 504 | Deadline expired before operation could complete.
|NOT_FOUND | 404 | Some requested entity (e.g., file or directory) was not found.
|ALREADY_EXISTS | 409 | Some entity that we attempted to create (e.g., file or directory) already exists.
|PERMISSION_DENIED | 403 | The caller does not have permission to execute the specified operation.
|RESOURCE_EXHAUSTED | 429 | Some resource has been exhausted, perhaps a per-user quota, or perhaps the entire file system is out of space.
|FAILED_PRECONDITION | 400 | Operation was rejected because the system is not in a state required for the operation's execution
|ABORTED | 409 | The operation was aborted, typically due to a concurrency issue like sequencer check failures, transaction aborts, etc.
|OUT_OF_RANGE | 400 | Operation was attempted past the valid range.
|UNIMPLEMENTED | 501 | Operation is not implemented or not supported/enabled in this service.
|INTERNAL | 500 | Internal errors. This means that some invariants expected by the underlying system have been broken.
|UNAVAILABLE | 503 | The service is currently unavailable.
|DATA_LOSS | 500 | Unrecoverable data loss or corruption.
|UNAUTHENTICATED | 401 | The request does not have valid authentication credentials for the operation.
|===

=== Server request/response API

The gRPC request/response server API provides an alternative way to interact with a client without the need of extending
a Java class.

==== Request/response

Each service method is processed by a handler, the handler is bound using a `{@link io.vertx.grpc.common.ServiceMethod}`.

[source,java]
----
{@link examples.GrpcServerExamples#requestResponse}
----

`{@link io.vertx.grpc.common.ServiceMethod}` constants are <<ServiceMethodConstants,generated>> by the Vert.x gRPC protoc plugin.

==== Streaming request

You can set handlers to process request events

[source,java]
----
{@link examples.GrpcServerExamples#streamingRequest}
----

==== Streaming response

A streaming response involves calling `{@link io.vertx.grpc.server.GrpcServerResponse#write}` for each element of the stream
and using `{@link io.vertx.grpc.server.GrpcServerResponse#end()}` to end the stream

[source,java]
----
{@link examples.GrpcServerExamples#streamingResponse}
----

==== Bidi request/response

A bidi request/response is simply the combination of a streaming request and a streaming response

[source,java]
----
{@link examples.GrpcServerExamples#bidi}
----

NOTE: The gRPC-Web protocol does not support bidirectional streaming.

=== Flow control

Request and response are back pressured Vert.x streams.

You can pause/resume/fetch a request

[source,java]
----
{@link examples.GrpcServerExamples#requestFlowControl}
----

You can check the writability of a response and set a drain handler

[source,java]
----
{@link examples.GrpcServerExamples#responseFlowControl}
----

=== Timeout and deadlines

The gRPC server handles timeout and deadlines.

Whenever the service receives a request indicating a timeout, the timeout can be retrieved.

[source,java]
----
{@link examples.GrpcServerExamples#checkTimeout}
----

By default, the server

- does not schedule automatically a deadline for a given request
- does not automatically propagate the deadline to a vertx client

The server can schedule deadlines: when a request carries a timeout, the server schedules
locally a timer to cancel the request when the response has not been sent in time.

The server can propagate deadlines: when a request carries a timeout, the server calculate the deadline
and associate the current server request with this deadline. Vert.x gRPC client can use this deadline to compute
a timeout to be sent and cascade the timeout to another gRPC server.

[source,java]
----
{@link examples.GrpcServerExamples#deadlineConfiguration}
----

=== JSON wire format

gRPC implicitly assumes the usage of the https://protobuf.dev[Protobuf] wire format.

The Vert.x gRPC server supports the JSON wire format as well.

You can use a JSON service method to bind a service method accepting requests carrying the `application/grpc+json` content-type.

[source,java]
----
{@link examples.GrpcServerExamples#jsonWireFormat01}
----

The `com.google.protobuf:protobuf-java-util` library performs the JSON encoding/decoding.

NOTE: the same service method can be bound twice with Protobuf and JSON wire formats.

Anemic JSON is also supported with Vert.x `JsonObject`

[source,java]
----
{@link examples.GrpcServerExamples#jsonWireFormat02}
----

=== Compression

You can compress response messages by setting the response encoding *prior* before sending any message

[source,java]
----
{@link examples.GrpcServerExamples#responseCompression}
----

NOTE: Compression is not supported over the gRPC-Web protocol.

=== Decompression

Decompression is done transparently by the server when the client send encoded requests.

NOTE: Decompression is not supported over the gRPC-Web protocol.

=== Transcoding

To create HTTP/gRPC bindings for a given service method.

1. Create a `MethodTranscodingOptions` instance
2. Create a transcoding service method
3. Register the call handler as usual

[source,java]
----
{@link examples.GrpcServerExamples#transcodingRequestResponse}
----

NOTE: the service method must use the JSON wire format

To test gRPC transcoding, you can use a tool like `curl` to send HTTP requests to your gRPC service.

For example, to send a `GET` request to the `/v1/hello/Steve` endpoint:

[source]
----
curl -X GET http://localhost:8080/v1/hello/Steve
----

=== Message level API

The server provides a message level API to interact directly with protobuf encoded gRPC messages.

TIP: the server message level API can be used with the client message level API to write a gRPC reverse proxy

Such API is useful when you are not interested in the content of the messages, and instead you want to forward them to
another service, e.g. you are writing a proxy.

[source,java]
----
{@link examples.GrpcServerExamples#protobufLevelAPI}
----

You can also set a `messageHandler` to handle `{@link io.vertx.grpc.common.GrpcMessage}`, such messages preserve the
client encoding, which is useful the service you are forwarding to can handle compressed messages directly, in this case
the message does not need to be decompressed and compressed again.

[source,java]
----
{@link examples.GrpcServerExamples#messageLevelAPI}
----

The `{@link io.vertx.grpc.server.GrpcServerResponse#writeMessage}` and `{@link io.vertx.grpc.server.GrpcServerResponse#endMessage}` will
handle the message encoding:

- when the message uses the response encoding, the message is sent as is
- when the message uses a different encoding, it will be encoded, e.g. compressed or uncompressed

=== Server stub API

In addition to the request/response API, the Vert.x gRPC protoc plugin idiomatic service stubs.

Each service comes in two flavors, you can override the method you like depending on the style.

==== Unary services

Unary services can return a Vert.x `Future`

[source,java]
----
{@link examples.GrpcServerExamples#unaryStub1}
----

or process a Vert.x `Promise`

[source,java]
----
{@link examples.GrpcServerExamples#unaryStub2}
----

In both case you need to bind the stub to an existing `GrpcServer`

[source,java]
----
{@link examples.GrpcServerExamples#unaryStub3}
----

You can also specify the JSON wire format when binding a stub.

[source,java]
----
{@link examples.GrpcServerExamples#unaryStub4}
----

The server will accept the `application/grpc+json` requests.

==== Streaming requests

Streaming requests are implemented with a `ReadStream`:

[source,java]
----
{@link examples.GrpcServerExamples#streamingRequestStub}
----

==== Streaming responses

Streaming responses are implemented with Vert.x streams and comes in two flavors.

You can return a Vert.x `ReadStream` and let the service send it for you:

[source,java]
----
{@link examples.GrpcServerExamples#streamingResponseStub1}
----

or you can process a `WriteStream`:

[source,java]
----
{@link examples.GrpcServerExamples#streamingResponseStub2}
----
