// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: streaming.proto
// Protobuf Java Version: 4.29.3

package io.vertx.grpc.sandbox.streaming;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:streaming.Empty)
    com.google.protobuf.MessageOrBuilder {
}
