// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: streaming.proto
// Protobuf Java Version: 4.29.3

package io.vertx.grpc.sandbox.streaming;

public final class StreamingOuterClass {
  private StreamingOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      StreamingOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_streaming_Item_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_streaming_Item_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_streaming_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_streaming_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017streaming.proto\022\tstreaming\"\025\n\004Item\022\r\n\005" +
      "value\030\001 \001(\t\"\007\n\005Empty2\310\001\n\tStreaming\022+\n\005Un" +
      "ary\022\017.streaming.Item\032\017.streaming.Item\"\000\022" +
      "/\n\006Source\022\020.streaming.Empty\032\017.streaming." +
      "Item\"\0000\001\022-\n\004Sink\022\017.streaming.Item\032\020.stre" +
      "aming.Empty\"\000(\001\022.\n\004Pipe\022\017.streaming.Item" +
      "\032\017.streaming.Item\"\000(\0010\001B#\n\037io.vertx.grpc" +
      ".sandbox.streamingP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_streaming_Item_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_streaming_Item_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_streaming_Item_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_streaming_Empty_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_streaming_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_streaming_Empty_descriptor,
        new java.lang.String[] { });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
