// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: docs.proto
// Protobuf Java Version: 4.29.3

package examples.grpc;

public final class Docs {
  private Docs() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      Docs.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_examples_grpc_HelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_examples_grpc_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_examples_grpc_HelloReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_examples_grpc_HelloReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_examples_grpc_Item_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_examples_grpc_Item_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_examples_grpc_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_examples_grpc_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ndocs.proto\022\rexamples.grpc\032\034google/api/" +
      "annotations.proto\032\027google/api/client.pro" +
      "to\"\034\n\014HelloRequest\022\014\n\004name\030\001 \001(\t\"\035\n\nHell" +
      "oReply\022\017\n\007message\030\001 \001(\t\"\025\n\004Item\022\r\n\005value" +
      "\030\001 \001(\t\"\007\n\005Empty2n\n\007Greeter\022c\n\010SayHello\022\033" +
      ".examples.grpc.HelloRequest\032\031.examples.g" +
      "rpc.HelloReply\"\037\332A\004name\202\323\344\223\002\022\022\020/v1/hello" +
      "/{name}2\263\001\n\tStreaming\0227\n\006Source\022\024.exampl" +
      "es.grpc.Empty\032\023.examples.grpc.Item\"\0000\001\0225" +
      "\n\004Sink\022\023.examples.grpc.Item\032\024.examples.g" +
      "rpc.Empty\"\000(\001\0226\n\004Pipe\022\023.examples.grpc.It" +
      "em\032\023.examples.grpc.Item\"\000(\0010\001B\021\n\rexample" +
      "s.grpcP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
          com.google.api.ClientProto.getDescriptor(),
        });
    internal_static_examples_grpc_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_examples_grpc_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_examples_grpc_HelloRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_examples_grpc_HelloReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_examples_grpc_HelloReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_examples_grpc_HelloReply_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_examples_grpc_Item_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_examples_grpc_Item_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_examples_grpc_Item_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_examples_grpc_Empty_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_examples_grpc_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_examples_grpc_Empty_descriptor,
        new java.lang.String[] { });
    descriptor.resolveAllFeaturesImmutable();
    com.google.api.AnnotationsProto.getDescriptor();
    com.google.api.ClientProto.getDescriptor();
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.AnnotationsProto.http);
    registry.add(com.google.api.ClientProto.methodSignature);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
