// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: docs.proto
// Protobuf Java Version: 4.29.3

package examples.grpc;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:examples.grpc.Empty)
    com.google.protobuf.MessageOrBuilder {
}
