// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: docs.proto
// Protobuf Java Version: 4.33.5

package examples.grpc;

@com.google.protobuf.Generated
public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:examples.grpc.Empty)
    com.google.protobuf.MessageOrBuilder {
}
