// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: streaming.proto
// Protobuf Java Version: 4.27.2

package examples;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:streaming.Empty)
    com.google.protobuf.MessageOrBuilder {
}
