package io.vertx.grpc.plugin.generation;

import java.util.Collections;
import java.util.EnumSet;
import java.util.Set;

/**
 * Represents options for configuring code generation.
 * <p>
 * This class provides various configuration options to control the generation of code artifacts during the build or runtime process. Each option has a default value, and the
 * options can be customized using the provided setter methods.
 * <p>
 * Configuration options include flags for generating client code, service code, IO-related code, and transcoding, as well as annotations for the Vert.x code generator.
 * Additionally, a service prefix can be defined to customize the naming of services.
 */
public class GenerationOptions {

  /**
   * The default configuration for determining whether client generation should be enabled. By default, client generation is disabled.
   */
  public static final boolean DEFAULT_GENERATE_CLIENT = false;

  /**
   * Default value indicating whether the generation of service classes is enabled. By default, this is set to {@code false}, meaning service class generation is disabled unless
   * explicitly configured.
   */
  public static final boolean DEFAULT_GENERATE_SERVICE = false;

  /**
   * Specifies the default setting for whether IO-related files should be generated by the generation process. This flag serves as a default value for controlling the inclusion of
   * IO generation features. By default, it is set to {@code false}, indicating that IO-related files will not be generated unless explicitly enabled.
   */
  public static final boolean DEFAULT_GENERATE_IO = false;

  /**
   * Indicates whether transcoding generation is enabled by default. When set to true, it implies that the generation process should include support for transcoding features. This
   * is a configurable option in the generation process and can be overridden based on specific requirements.
   */
  public static final boolean DEFAULT_GENERATE_TRANSCODING = true;

  /**
   * A default configuration flag that determines whether Vert.x generator annotations should be included during the code generation process. By default, the value is set to false,
   * implying that the generator annotations are not added unless explicitly enabled.
   */
  public static final boolean DEFAULT_GENERATE_VERTX_GENERATOR_ANNOTATIONS = false;

  /**
   * The default prefix used for generated service files. This value serves as the initial prefix applied to service-related entities during the code generation process.
   */
  public static final String DEFAULT_SERVICE_PREFIX = "";

  private boolean generateClient;
  private boolean generateService;
  private boolean generateIo;
  private boolean generateTranscoding;
  private boolean generateVertxGeneratorAnnotations;
  private String servicePrefix;
  private Set<SchemaOutputFormat> schemaOutputFormats;
  private boolean schemaAllowMerge;
  private String schemaConfigFile;

  public GenerationOptions() {
    this.generateClient = DEFAULT_GENERATE_CLIENT;
    this.generateService = DEFAULT_GENERATE_SERVICE;
    this.generateIo = DEFAULT_GENERATE_IO;
    this.generateTranscoding = DEFAULT_GENERATE_TRANSCODING;
    this.generateVertxGeneratorAnnotations = DEFAULT_GENERATE_VERTX_GENERATOR_ANNOTATIONS;
    this.servicePrefix = DEFAULT_SERVICE_PREFIX;
    this.schemaOutputFormats = EnumSet.noneOf(SchemaOutputFormat.class);
    this.schemaAllowMerge = true;
    this.schemaConfigFile = null;
  }

  /**
   * Determines if the generation of client-specific code is enabled.
   *
   * @return true if client generation is enabled, false otherwise
   */
  public boolean isGenerateClient() {
    return generateClient;
  }

  /**
   * Sets whether the client generation feature is enabled or disabled.
   *
   * @param generateClient a boolean value where {@code true} enables client generation and {@code false} disables it
   * @return the current {@code GenerationOptions} instance to allow method chaining
   */
  public GenerationOptions setGenerateClient(boolean generateClient) {
    this.generateClient = generateClient;
    return this;
  }

  /**
   * Determines whether service-related code generation is enabled.
   *
   * @return true if service generation is enabled; false otherwise
   */
  public boolean isGenerateService() {
    return generateService;
  }

  /**
   * Configures whether the service generation is enabled or disabled.
   *
   * @param generateService a boolean value indicating whether to enable (true) or disable (false) the generation of services.
   * @return the current instance of {@code GenerationOptions}, allowing for method chaining.
   */
  public GenerationOptions setGenerateService(boolean generateService) {
    this.generateService = generateService;
    return this;
  }

  /**
   * Determines if IO-related code generation is enabled.
   *
   * @return true if IO-related code should be generated, false otherwise.
   */
  public boolean isGenerateIo() {
    return generateIo;
  }

  /**
   * Sets the generation of IO files based on the given flag.
   *
   * @param generateIo a boolean flag that determines whether IO files should be generated
   * @return the current instance of GenerationOptions for method chaining
   */
  public GenerationOptions setGenerateIo(boolean generateIo) {
    this.generateIo = generateIo;
    return this;
  }

  /**
   * Determines whether the generation of transcoding features is enabled.
   *
   * @return true if transcoding generation is enabled, false otherwise.
   */
  public boolean isGenerateTranscoding() {
    return generateTranscoding;
  }

  /**
   * Sets whether transcoding generation is enabled or disabled.
   *
   * @param generateTranscoding a boolean indicating whether to enable (true) or disable (false) transcoding generation.
   * @return the current {@code GenerationOptions} instance to allow method chaining.
   */
  public GenerationOptions setGenerateTranscoding(boolean generateTranscoding) {
    this.generateTranscoding = generateTranscoding;
    return this;
  }

  /**
   * Determines whether Vert.x generator annotations should be generated.
   *
   * @return true if Vert.x generator annotations should be generated, false otherwise.
   */
  public boolean isGenerateVertxGeneratorAnnotations() {
    return generateVertxGeneratorAnnotations;
  }

  /**
   * Configures whether Vert.x generator annotations should be generated.
   *
   * @param generateVertxGeneratorAnnotations a boolean indicating whether to enable or disable the generation of Vert.x generator annotations
   * @return the updated {@code GenerationOptions} instance
   */
  public GenerationOptions setGenerateVertxGeneratorAnnotations(boolean generateVertxGeneratorAnnotations) {
    this.generateVertxGeneratorAnnotations = generateVertxGeneratorAnnotations;
    return this;
  }

  /**
   * Retrieves the service prefix used for naming or identification purposes in the context of the generation process.
   *
   * @return the service prefix as a {@code String}
   */
  public String getServicePrefix() {
    return servicePrefix;
  }

  /**
   * Sets the service prefix to be used for generation.
   *
   * @param servicePrefix the service prefix to set
   * @return the current instance of {@code GenerationOptions} for method chaining
   */
  public GenerationOptions setServicePrefix(String servicePrefix) {
    this.servicePrefix = servicePrefix;
    return this;
  }

  /**
   * Determines whether any OpenAPI format generation is enabled.
   *
   * @return true if at least one OpenAPI format is configured for generation, false otherwise.
   */
  public boolean isGenerateOpenApi() {
    return !schemaOutputFormats.isEmpty();
  }

  /**
   * Determines whether OpenAPI JSON spec generation is enabled.
   *
   * @return true if OpenAPI JSON generation is enabled, false otherwise.
   */
  public boolean isGenerateOpenApiJson() {
    return schemaOutputFormats.contains(SchemaOutputFormat.OPEN_API_JSON);
  }

  /**
   * Determines whether OpenAPI YAML spec generation is enabled.
   *
   * @return true if OpenAPI YAML generation is enabled, false otherwise.
   */
  public boolean isGenerateOpenApiYaml() {
    return schemaOutputFormats.contains(SchemaOutputFormat.OPEN_API_YAML);
  }

  /**
   * Returns the set of schema output formats configured for generation.
   *
   * @return an unmodifiable set of schema output formats
   */
  public Set<SchemaOutputFormat> getSchemaOutputFormats() {
    return Collections.unmodifiableSet(schemaOutputFormats);
  }

  /**
   * Sets the schema output formats to generate.
   *
   * @param formats the set of schema output formats to generate
   * @return the current {@code GenerationOptions} instance to allow method chaining
   */
  public GenerationOptions setSchemaOutputFormats(Set<SchemaOutputFormat> formats) {
    this.schemaOutputFormats = formats != null ? EnumSet.copyOf(formats) : EnumSet.noneOf(SchemaOutputFormat.class);
    return this;
  }

  /**
   * Adds a schema output format to generate.
   *
   * @param format the schema output format to add
   * @return the current {@code GenerationOptions} instance to allow method chaining
   */
  public GenerationOptions addSchemaOutputFormat(SchemaOutputFormat format) {
    if (format != null) {
      this.schemaOutputFormats.add(format);
    }
    return this;
  }

  /**
   * Determines whether OpenAPI specs should be merged into a single file.
   *
   * @return true if specs should be merged, false for per-service files
   */
  public boolean isSchemaAllowMerge() {
    return schemaAllowMerge;
  }

  /**
   * Sets whether OpenAPI specs should be merged into a single file.
   *
   * @param schemaAllowMerge true to merge all services into one file, false for per-service files
   * @return the current {@code GenerationOptions} instance to allow method chaining
   */
  public GenerationOptions setSchemaAllowMerge(boolean schemaAllowMerge) {
    this.schemaAllowMerge = schemaAllowMerge;
    return this;
  }

  /**
   * Returns the path to the OpenAPI configuration file.
   * The configuration file should be a YAML or JSON file containing OpenAPI specification
   * fields (info, servers, security, tags, externalDocs, etc.) that will be merged with
   * the generated specification.
   *
   * @return the path to the configuration file, or null if not set
   */
  public String getSchemaConfigFile() {
    return schemaConfigFile;
  }

  /**
   * Sets the path to the OpenAPI configuration file.
   * The configuration file should be a YAML or JSON file containing OpenAPI specification
   * fields that will be merged with the generated specification.
   *
   * @param schemaConfigFile the path to the configuration file
   * @return the current {@code GenerationOptions} instance to allow method chaining
   */
  public GenerationOptions setSchemaConfigFile(String schemaConfigFile) {
    this.schemaConfigFile = schemaConfigFile;
    return this;
  }

  /**
   * Returns a string representation of this GenerationOptions instance, including all configuration fields.
   *
   * @return a string representation of this object
   */
  @Override
  public String toString() {
    return "GenerationOptions{" +
      "generateClient=" + generateClient +
      ", generateService=" + generateService +
      ", generateIo=" + generateIo +
      ", generateTranscoding=" + generateTranscoding +
      ", generateVertxGeneratorAnnotations=" + generateVertxGeneratorAnnotations +
      ", servicePrefix='" + servicePrefix + '\'' +
      ", schemaOutputFormats=" + schemaOutputFormats +
      ", schemaAllowMerge=" + schemaAllowMerge +
      ", schemaConfigFile='" + schemaConfigFile + '\'' +
      '}';
  }
}
